[36m[2022-10-21 11:17:20 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-10-21 11:17:20 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-10-21 11:17:20 DEBUG] [cli:117][39m Using settings file '/home/thushan/.chaostoolkit/settings.yaml'
[36m[2022-10-21 11:17:21 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/thushan/.chaostoolkit/settings.yaml'.
[36m[2022-10-21 11:17:21 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-10-21 11:17:21 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-10-21 11:17:21 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-10-21 11:17:21 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-10-21 11:17:21 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-10-21 11:17:21 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-10-21 11:17:21 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-10-21 11:17:21 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-10-21 11:17:21 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-10-21 11:17:21 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-10-21 11:17:21 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-10-21 11:17:21 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-10-21 11:17:21 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-10-21 11:17:21 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-10-21 11:17:21 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-10-21 11:17:21 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-10-21 11:17:21 INFO] [run:320][39m Running experiment: Employee when database is down
[36m[2022-10-21 11:17:21 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-10-21 11:17:22 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-10-21 11:17:22 INFO] [run:348][39m Rollbacks strategy: default
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-10-21 11:17:22 DEBUG] [run:506][39m Running steady-state hypothesis before the method
[32m[2022-10-21 11:17:22 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:17:22 INFO] [activity:204][39m Probe: we-can-retrieve-employee-data
[36m[2022-10-21 11:17:22 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Fri, 21 Oct 2022 05:47:22 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': []}'
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:17:22 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[32m[2022-10-21 11:17:22 INFO] [hypothesis:231][39m Steady state hypothesis is met!
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[32m[2022-10-21 11:17:22 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:17:22 INFO] [activity:204][39m Action: enable_chaosmonkey
[36m[2022-10-21 11:17:22 DEBUG] [python:33][39m Activity 'enable_chaosmonkey' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-21 11:17:22 DEBUG] [activity:221][39m   => succeeded with 'Chaos Monkey is enabled'
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:17:22 INFO] [activity:204][39m Action: configure_assaults
[36m[2022-10-21 11:17:22 DEBUG] [python:33][39m Activity 'configure_assaults' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-21 11:17:22 DEBUG] [activity:221][39m   => succeeded with 'Assault config has changed'
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:17:22 INFO] [activity:204][39m Action: configure_repository_watcher
[36m[2022-10-21 11:17:22 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'text/plain;charset=UTF-8', 'Content-Length': '26', 'Date': 'Fri, 21 Oct 2022 05:47:22 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': 'Watcher config has changed'}'
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-10-21 11:17:22 DEBUG] [run:536][39m Running steady-state hypothesis after the method
[32m[2022-10-21 11:17:22 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:17:22 INFO] [activity:204][39m Probe: we-can-retrieve-employee-data
[36m[2022-10-21 11:17:22 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Fri, 21 Oct 2022 05:47:22 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': []}'
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:17:22 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[32m[2022-10-21 11:17:22 INFO] [hypothesis:231][39m Steady state hypothesis is met!
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[32m[2022-10-21 11:17:22 INFO] [run:893][39m Let's rollback...
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-10-21 11:17:22 INFO] [rollback:30][39m Rollback: disable_chaosmonkey
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:17:22 INFO] [activity:204][39m Action: disable_chaosmonkey
[36m[2022-10-21 11:17:22 DEBUG] [python:33][39m Activity 'disable_chaosmonkey' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-21 11:17:22 DEBUG] [activity:221][39m   => succeeded with 'Chaos Monkey is disabled'
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-10-21 11:17:22 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-10-21 11:17:22 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-10-21 11:17:22 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-10-21 11:17:22 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-10-21 11:21:17 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-10-21 11:21:17 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-10-21 11:21:17 DEBUG] [cli:117][39m Using settings file '/home/thushan/.chaostoolkit/settings.yaml'
[36m[2022-10-21 11:21:18 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/thushan/.chaostoolkit/settings.yaml'.
[36m[2022-10-21 11:21:18 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-10-21 11:21:18 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-10-21 11:21:18 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-10-21 11:21:18 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-10-21 11:21:18 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-10-21 11:21:18 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-10-21 11:21:18 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-10-21 11:21:18 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-10-21 11:21:18 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-10-21 11:21:18 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-10-21 11:21:18 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-10-21 11:21:18 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-10-21 11:21:18 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-10-21 11:21:18 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-10-21 11:21:18 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-10-21 11:21:18 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-10-21 11:21:18 INFO] [run:320][39m Running experiment: Employee when database is down
[36m[2022-10-21 11:21:18 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-10-21 11:21:18 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-10-21 11:21:18 INFO] [run:348][39m Rollbacks strategy: default
[36m[2022-10-21 11:21:18 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-10-21 11:21:18 DEBUG] [run:506][39m Running steady-state hypothesis before the method
[32m[2022-10-21 11:21:18 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-10-21 11:21:18 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-10-21 11:21:18 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:21:18 INFO] [activity:204][39m Probe: we-can-retrieve-employee-data
[36m[2022-10-21 11:21:18 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Fri, 21 Oct 2022 05:51:18 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': []}'
[36m[2022-10-21 11:21:18 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:21:18 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[32m[2022-10-21 11:21:18 INFO] [hypothesis:231][39m Steady state hypothesis is met!
[36m[2022-10-21 11:21:18 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[32m[2022-10-21 11:21:18 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-10-21 11:21:18 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-10-21 11:21:18 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:21:18 INFO] [activity:204][39m Action: enable_chaosmonkey
[36m[2022-10-21 11:21:18 DEBUG] [python:33][39m Activity 'enable_chaosmonkey' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-21 11:21:18 DEBUG] [activity:221][39m   => succeeded with 'Chaos Monkey is enabled'
[36m[2022-10-21 11:21:18 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:21:18 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:21:18 INFO] [activity:204][39m Action: configure_assaults
[36m[2022-10-21 11:21:18 DEBUG] [python:33][39m Activity 'configure_assaults' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-21 11:21:19 DEBUG] [activity:221][39m   => succeeded with 'Assault config has changed'
[36m[2022-10-21 11:21:19 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:21:19 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:21:19 INFO] [activity:204][39m Action: configure_repository_watcher
[36m[2022-10-21 11:21:19 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'text/plain;charset=UTF-8', 'Content-Length': '26', 'Date': 'Fri, 21 Oct 2022 05:51:18 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': 'Watcher config has changed'}'
[36m[2022-10-21 11:21:19 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:21:19 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-10-21 11:21:19 DEBUG] [run:536][39m Running steady-state hypothesis after the method
[32m[2022-10-21 11:21:19 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-10-21 11:21:19 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-10-21 11:21:19 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:21:19 INFO] [activity:204][39m Probe: we-can-retrieve-employee-data
[36m[2022-10-21 11:21:19 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Fri, 21 Oct 2022 05:51:18 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': []}'
[36m[2022-10-21 11:21:19 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:21:19 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[32m[2022-10-21 11:21:19 INFO] [hypothesis:231][39m Steady state hypothesis is met!
[36m[2022-10-21 11:21:19 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[32m[2022-10-21 11:21:19 INFO] [run:893][39m Let's rollback...
[36m[2022-10-21 11:21:19 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-10-21 11:21:19 INFO] [rollback:30][39m Rollback: disable_chaosmonkey
[36m[2022-10-21 11:21:19 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:21:19 INFO] [activity:204][39m Action: disable_chaosmonkey
[36m[2022-10-21 11:21:19 DEBUG] [python:33][39m Activity 'disable_chaosmonkey' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-21 11:21:19 DEBUG] [activity:221][39m   => succeeded with 'Chaos Monkey is disabled'
[36m[2022-10-21 11:21:19 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:21:19 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-10-21 11:21:19 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-10-21 11:21:19 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-10-21 11:21:19 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-10-21 11:21:19 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-10-21 11:26:46 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-10-21 11:26:46 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-10-21 11:26:46 DEBUG] [cli:117][39m Using settings file '/home/thushan/.chaostoolkit/settings.yaml'
[36m[2022-10-21 11:26:48 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/thushan/.chaostoolkit/settings.yaml'.
[36m[2022-10-21 11:26:48 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-10-21 11:26:48 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-10-21 11:26:48 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-10-21 11:26:48 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-10-21 11:26:48 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-10-21 11:26:48 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-10-21 11:26:48 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-10-21 11:26:48 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-10-21 11:26:48 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-10-21 11:26:48 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-10-21 11:26:48 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-10-21 11:26:48 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-10-21 11:26:48 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-10-21 11:26:48 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-10-21 11:26:48 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-10-21 11:26:48 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-10-21 11:26:48 INFO] [run:320][39m Running experiment: Employee when database is down
[36m[2022-10-21 11:26:48 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-10-21 11:26:48 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-10-21 11:26:48 INFO] [run:348][39m Rollbacks strategy: default
[36m[2022-10-21 11:26:48 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-10-21 11:26:48 DEBUG] [run:506][39m Running steady-state hypothesis before the method
[32m[2022-10-21 11:26:48 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-10-21 11:26:48 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-10-21 11:26:48 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:26:48 INFO] [activity:204][39m Probe: we-can-retrieve-employee-data
[36m[2022-10-21 11:26:49 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Fri, 21 Oct 2022 05:56:49 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': []}'
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:26:49 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[32m[2022-10-21 11:26:49 INFO] [hypothesis:231][39m Steady state hypothesis is met!
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[32m[2022-10-21 11:26:49 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:26:49 INFO] [activity:204][39m Action: enable_chaosmonkey
[36m[2022-10-21 11:26:49 DEBUG] [python:33][39m Activity 'enable_chaosmonkey' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-21 11:26:49 DEBUG] [activity:221][39m   => succeeded with 'Chaos Monkey is enabled'
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:26:49 INFO] [activity:204][39m Action: configure_assaults
[36m[2022-10-21 11:26:49 DEBUG] [python:33][39m Activity 'configure_assaults' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-21 11:26:49 DEBUG] [activity:221][39m   => succeeded with 'Assault config has changed'
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:26:49 INFO] [activity:204][39m Action: configure_repository_watcher
[36m[2022-10-21 11:26:49 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'text/plain;charset=UTF-8', 'Content-Length': '26', 'Date': 'Fri, 21 Oct 2022 05:56:49 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': 'Watcher config has changed'}'
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-10-21 11:26:49 DEBUG] [run:536][39m Running steady-state hypothesis after the method
[32m[2022-10-21 11:26:49 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:26:49 INFO] [activity:204][39m Probe: we-can-retrieve-employee-data
[36m[2022-10-21 11:26:49 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Fri, 21 Oct 2022 05:56:49 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': []}'
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:26:49 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[32m[2022-10-21 11:26:49 INFO] [hypothesis:231][39m Steady state hypothesis is met!
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[32m[2022-10-21 11:26:49 INFO] [run:893][39m Let's rollback...
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-10-21 11:26:49 INFO] [rollback:30][39m Rollback: disable_chaosmonkey
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:26:49 INFO] [activity:204][39m Action: disable_chaosmonkey
[36m[2022-10-21 11:26:49 DEBUG] [python:33][39m Activity 'disable_chaosmonkey' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-21 11:26:49 DEBUG] [activity:221][39m   => succeeded with 'Chaos Monkey is disabled'
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-10-21 11:26:49 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-10-21 11:26:49 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-10-21 11:26:49 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-10-21 11:26:49 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-10-21 11:27:50 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-10-21 11:27:50 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-10-21 11:27:50 DEBUG] [cli:117][39m Using settings file '/home/thushan/.chaostoolkit/settings.yaml'
[36m[2022-10-21 11:27:51 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/thushan/.chaostoolkit/settings.yaml'.
[36m[2022-10-21 11:27:51 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-10-21 11:27:51 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-10-21 11:27:51 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-10-21 11:27:51 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-10-21 11:27:51 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-10-21 11:27:51 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-10-21 11:27:51 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-10-21 11:27:51 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-10-21 11:27:51 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-10-21 11:27:51 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-10-21 11:27:51 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-10-21 11:27:51 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-10-21 11:27:51 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-10-21 11:27:51 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-10-21 11:27:51 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-10-21 11:27:51 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-10-21 11:27:51 INFO] [run:320][39m Running experiment: Employee when database is down
[36m[2022-10-21 11:27:51 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-10-21 11:27:51 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-10-21 11:27:51 INFO] [run:348][39m Rollbacks strategy: default
[36m[2022-10-21 11:27:51 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-10-21 11:27:51 DEBUG] [run:506][39m Running steady-state hypothesis before the method
[32m[2022-10-21 11:27:51 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-10-21 11:27:51 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-10-21 11:27:51 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:27:51 INFO] [activity:204][39m Probe: we-can-retrieve-employee-data
[36m[2022-10-21 11:27:54 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Fri, 21 Oct 2022 05:57:54 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': []}'
[36m[2022-10-21 11:27:54 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:27:54 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[32m[2022-10-21 11:27:54 INFO] [hypothesis:231][39m Steady state hypothesis is met!
[36m[2022-10-21 11:27:54 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[32m[2022-10-21 11:27:54 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-10-21 11:27:54 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-10-21 11:27:54 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:27:54 INFO] [activity:204][39m Action: enable_chaosmonkey
[36m[2022-10-21 11:27:54 DEBUG] [python:33][39m Activity 'enable_chaosmonkey' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-21 11:27:54 DEBUG] [activity:221][39m   => succeeded with 'Chaos Monkey is enabled'
[36m[2022-10-21 11:27:54 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:27:54 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:27:54 INFO] [activity:204][39m Action: configure_assaults
[36m[2022-10-21 11:27:54 DEBUG] [python:33][39m Activity 'configure_assaults' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-21 11:27:55 DEBUG] [activity:221][39m   => succeeded with 'Assault config has changed'
[36m[2022-10-21 11:27:55 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:27:55 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:27:55 INFO] [activity:204][39m Action: configure_repository_watcher
[36m[2022-10-21 11:27:55 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'text/plain;charset=UTF-8', 'Content-Length': '26', 'Date': 'Fri, 21 Oct 2022 05:57:54 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': 'Watcher config has changed'}'
[36m[2022-10-21 11:27:55 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:27:55 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-10-21 11:27:55 DEBUG] [run:536][39m Running steady-state hypothesis after the method
[32m[2022-10-21 11:27:55 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-10-21 11:27:55 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-10-21 11:27:55 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-21 11:27:55 INFO] [activity:204][39m Probe: we-can-retrieve-employee-data
[36m[2022-10-21 11:27:55 DEBUG] [activity:221][39m   => succeeded with '{'status': 500, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Fri, 21 Oct 2022 05:57:54 GMT', 'Connection': 'close'}, 'body': {'timestamp': '2022-10-21T05:57:55.165+0000', 'status': 500, 'error': 'Internal Server Error', 'message': 'No message available', 'path': '/employee/all'}}'
[36m[2022-10-21 11:27:55 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-21 11:27:55 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[36m[2022-10-21 11:27:55 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[31m[2022-10-21 11:27:55 CRITICAL] [run:545][39m Steady state probe 'we-can-retrieve-employee-data' is not in the given tolerance so failing this experiment
[32m[2022-10-21 11:27:55 INFO] [run:458][39m Experiment ended with status: deviated
[32m[2022-10-21 11:27:55 INFO] [run:460][39m The steady-state has deviated, a weakness may have been discovered
[36m[2022-10-21 11:27:55 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-10-21 11:27:55 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-10-21 11:27:55 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-10-23 18:52:25 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-10-23 18:52:25 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-10-23 18:52:25 DEBUG] [cli:117][39m Using settings file '/home/thushan/.chaostoolkit/settings.yaml'
[36m[2022-10-23 18:52:27 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/thushan/.chaostoolkit/settings.yaml'.
[36m[2022-10-23 18:52:27 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-10-23 18:52:27 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-10-23 18:52:27 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-10-23 18:52:27 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-10-23 18:52:27 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-10-23 18:52:27 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-10-23 18:52:27 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-10-23 18:52:27 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-10-23 18:52:27 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-10-23 18:52:27 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-10-23 18:52:27 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-10-23 18:52:27 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-10-23 18:52:27 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-10-23 18:52:27 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-10-23 18:52:27 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-10-23 18:52:27 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-10-23 18:52:27 INFO] [run:320][39m Running experiment: Employee when database is down
[36m[2022-10-23 18:52:27 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-10-23 18:52:27 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-10-23 18:52:27 INFO] [run:348][39m Rollbacks strategy: default
[36m[2022-10-23 18:52:27 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-10-23 18:52:27 DEBUG] [run:506][39m Running steady-state hypothesis before the method
[32m[2022-10-23 18:52:27 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-10-23 18:52:27 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-10-23 18:52:27 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-23 18:52:27 INFO] [activity:204][39m Probe: we-can-retrieve-employee-data
[36m[2022-10-23 18:52:30 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Sun, 23 Oct 2022 13:22:30 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': []}'
[36m[2022-10-23 18:52:30 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-23 18:52:30 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[32m[2022-10-23 18:52:30 INFO] [hypothesis:231][39m Steady state hypothesis is met!
[36m[2022-10-23 18:52:30 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[32m[2022-10-23 18:52:30 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-10-23 18:52:30 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-10-23 18:52:30 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-23 18:52:30 INFO] [activity:204][39m Action: enable_chaosmonkey
[36m[2022-10-23 18:52:30 DEBUG] [python:33][39m Activity 'enable_chaosmonkey' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-23 18:52:30 DEBUG] [activity:221][39m   => succeeded with 'Chaos Monkey is enabled'
[36m[2022-10-23 18:52:30 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-23 18:52:30 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-23 18:52:30 INFO] [activity:204][39m Action: configure_assaults
[36m[2022-10-23 18:52:30 DEBUG] [python:33][39m Activity 'configure_assaults' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-23 18:52:30 DEBUG] [activity:221][39m   => succeeded with 'Assault config has changed'
[36m[2022-10-23 18:52:30 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-23 18:52:30 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-23 18:52:30 INFO] [activity:204][39m Action: configure_repository_watcher
[36m[2022-10-23 18:52:30 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'text/plain;charset=UTF-8', 'Content-Length': '26', 'Date': 'Sun, 23 Oct 2022 13:22:30 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': 'Watcher config has changed'}'
[36m[2022-10-23 18:52:30 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-23 18:52:30 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-10-23 18:52:30 DEBUG] [run:536][39m Running steady-state hypothesis after the method
[32m[2022-10-23 18:52:30 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-10-23 18:52:30 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-10-23 18:52:30 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-23 18:52:30 INFO] [activity:204][39m Probe: we-can-retrieve-employee-data
[36m[2022-10-23 18:52:30 DEBUG] [activity:221][39m   => succeeded with '{'status': 500, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Sun, 23 Oct 2022 13:22:30 GMT', 'Connection': 'close'}, 'body': {'timestamp': '2022-10-23T13:22:30.831+0000', 'status': 500, 'error': 'Internal Server Error', 'message': 'No message available', 'path': '/employee/all'}}'
[36m[2022-10-23 18:52:30 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-23 18:52:30 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[36m[2022-10-23 18:52:30 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[31m[2022-10-23 18:52:30 CRITICAL] [run:545][39m Steady state probe 'we-can-retrieve-employee-data' is not in the given tolerance so failing this experiment
[32m[2022-10-23 18:52:30 INFO] [run:458][39m Experiment ended with status: deviated
[32m[2022-10-23 18:52:30 INFO] [run:460][39m The steady-state has deviated, a weakness may have been discovered
[36m[2022-10-23 18:52:30 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-10-23 18:52:30 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-10-23 18:52:30 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-10-23 20:57:34 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-10-23 20:57:34 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-10-23 20:57:34 DEBUG] [cli:117][39m Using settings file '/home/thushan/.chaostoolkit/settings.yaml'
[36m[2022-10-23 20:57:38 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/thushan/.chaostoolkit/settings.yaml'.
[36m[2022-10-23 20:57:38 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-10-23 20:57:38 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-10-23 20:57:38 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-10-23 20:57:38 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-10-23 20:57:38 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-10-23 20:57:38 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-10-23 20:57:38 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-10-23 20:57:38 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-10-23 20:57:38 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-10-23 20:57:38 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-10-23 20:57:38 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-10-23 20:57:38 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-10-23 20:57:38 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-10-23 20:57:38 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-10-23 20:57:38 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-10-23 20:57:38 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-10-23 20:57:38 INFO] [run:320][39m Running experiment: Employee when database is down
[36m[2022-10-23 20:57:38 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-10-23 20:57:38 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-10-23 20:57:38 INFO] [run:348][39m Rollbacks strategy: default
[36m[2022-10-23 20:57:38 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-10-23 20:57:38 DEBUG] [run:506][39m Running steady-state hypothesis before the method
[32m[2022-10-23 20:57:38 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-10-23 20:57:38 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-10-23 20:57:38 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-23 20:57:38 INFO] [activity:204][39m Probe: we-can-retrieve-employee-data
[36m[2022-10-23 20:57:38 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Sun, 23 Oct 2022 15:27:38 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': []}'
[36m[2022-10-23 20:57:38 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-23 20:57:38 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[32m[2022-10-23 20:57:38 INFO] [hypothesis:231][39m Steady state hypothesis is met!
[36m[2022-10-23 20:57:38 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[32m[2022-10-23 20:57:38 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-10-23 20:57:38 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-10-23 20:57:38 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-23 20:57:38 INFO] [activity:204][39m Action: enable_chaosmonkey
[36m[2022-10-23 20:57:38 DEBUG] [python:33][39m Activity 'enable_chaosmonkey' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-23 20:57:38 DEBUG] [activity:221][39m   => succeeded with 'Chaos Monkey is enabled'
[36m[2022-10-23 20:57:38 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-23 20:57:38 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-23 20:57:38 INFO] [activity:204][39m Action: configure_assaults
[36m[2022-10-23 20:57:38 DEBUG] [python:33][39m Activity 'configure_assaults' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-23 20:57:39 DEBUG] [activity:221][39m   => succeeded with 'Assault config has changed'
[36m[2022-10-23 20:57:39 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-23 20:57:39 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-23 20:57:39 INFO] [activity:204][39m Action: configure_repository_watcher
[36m[2022-10-23 20:57:39 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'text/plain;charset=UTF-8', 'Content-Length': '26', 'Date': 'Sun, 23 Oct 2022 15:27:38 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': 'Watcher config has changed'}'
[36m[2022-10-23 20:57:39 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-23 20:57:39 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-10-23 20:57:39 DEBUG] [run:536][39m Running steady-state hypothesis after the method
[32m[2022-10-23 20:57:39 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-10-23 20:57:39 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-10-23 20:57:39 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-23 20:57:39 INFO] [activity:204][39m Probe: we-can-retrieve-employee-data
[36m[2022-10-23 20:57:39 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Sun, 23 Oct 2022 15:27:38 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': []}'
[36m[2022-10-23 20:57:39 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-23 20:57:39 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[32m[2022-10-23 20:57:39 INFO] [hypothesis:231][39m Steady state hypothesis is met!
[36m[2022-10-23 20:57:39 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[32m[2022-10-23 20:57:39 INFO] [run:893][39m Let's rollback...
[36m[2022-10-23 20:57:39 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-10-23 20:57:39 INFO] [rollback:30][39m Rollback: disable_chaosmonkey
[36m[2022-10-23 20:57:39 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-10-23 20:57:39 INFO] [activity:204][39m Action: disable_chaosmonkey
[36m[2022-10-23 20:57:39 DEBUG] [python:33][39m Activity 'disable_chaosmonkey' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-10-23 20:57:39 DEBUG] [activity:221][39m   => succeeded with 'Chaos Monkey is disabled'
[36m[2022-10-23 20:57:39 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-10-23 20:57:39 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-10-23 20:57:39 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-10-23 20:57:39 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-10-23 20:57:39 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-10-23 20:57:39 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-11-03 22:10:35 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-11-03 22:10:35 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-11-03 22:10:35 DEBUG] [cli:117][39m Using settings file '/home/thushan/.chaostoolkit/settings.yaml'
[36m[2022-11-03 22:10:37 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/thushan/.chaostoolkit/settings.yaml'.
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-11-03 22:10:37 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-11-03 22:10:37 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-11-03 22:10:37 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-11-03 22:10:37 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-11-03 22:10:37 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-11-03 22:10:37 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-11-03 22:10:37 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-11-03 22:10:37 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-11-03 22:10:37 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-11-03 22:10:37 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-11-03 22:10:37 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-11-03 22:10:37 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-11-03 22:10:37 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-11-03 22:10:37 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-11-03 22:10:37 INFO] [run:320][39m Running experiment: Employee when database is down
[36m[2022-11-03 22:10:37 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-11-03 22:10:37 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-11-03 22:10:37 INFO] [run:348][39m Rollbacks strategy: default
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-11-03 22:10:37 DEBUG] [run:506][39m Running steady-state hypothesis before the method
[32m[2022-11-03 22:10:37 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 22:10:37 INFO] [activity:204][39m Probe: we-can-retrieve-employee-data
[36m[2022-11-03 22:10:37 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Thu, 03 Nov 2022 16:40:37 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': []}'
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 22:10:37 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[32m[2022-11-03 22:10:37 INFO] [hypothesis:231][39m Steady state hypothesis is met!
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[32m[2022-11-03 22:10:37 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 22:10:37 INFO] [activity:204][39m Action: enable_chaosmonkey
[36m[2022-11-03 22:10:37 DEBUG] [python:33][39m Activity 'enable_chaosmonkey' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-11-03 22:10:37 DEBUG] [activity:221][39m   => succeeded with 'Chaos Monkey is enabled'
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 22:10:37 INFO] [activity:204][39m Action: configure_assaults
[36m[2022-11-03 22:10:37 DEBUG] [python:33][39m Activity 'configure_assaults' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-11-03 22:10:37 DEBUG] [activity:221][39m   => succeeded with 'Assault config has changed'
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 22:10:37 INFO] [activity:204][39m Action: configure_repository_watcher
[36m[2022-11-03 22:10:37 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'text/plain;charset=UTF-8', 'Content-Length': '26', 'Date': 'Thu, 03 Nov 2022 16:40:37 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': 'Watcher config has changed'}'
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-11-03 22:10:37 DEBUG] [run:536][39m Running steady-state hypothesis after the method
[32m[2022-11-03 22:10:37 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 22:10:37 INFO] [activity:204][39m Probe: we-can-retrieve-employee-data
[36m[2022-11-03 22:10:37 DEBUG] [activity:221][39m   => succeeded with '{'status': 500, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Thu, 03 Nov 2022 16:40:37 GMT', 'Connection': 'close'}, 'body': {'timestamp': '2022-11-03T16:40:37.877+0000', 'status': 500, 'error': 'Internal Server Error', 'message': 'No message available', 'path': '/employee/all'}}'
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 22:10:37 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[31m[2022-11-03 22:10:37 CRITICAL] [run:545][39m Steady state probe 'we-can-retrieve-employee-data' is not in the given tolerance so failing this experiment
[32m[2022-11-03 22:10:37 INFO] [run:458][39m Experiment ended with status: deviated
[32m[2022-11-03 22:10:37 INFO] [run:460][39m The steady-state has deviated, a weakness may have been discovered
[36m[2022-11-03 22:10:37 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-11-03 22:10:37 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-11-03 22:10:37 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-11-03 22:11:47 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-11-03 22:11:47 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-11-03 22:11:47 DEBUG] [cli:117][39m Using settings file '/home/thushan/.chaostoolkit/settings.yaml'
[36m[2022-11-03 22:11:48 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/thushan/.chaostoolkit/settings.yaml'.
[36m[2022-11-03 22:11:48 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-11-03 22:11:48 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-11-03 22:11:48 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-11-03 22:11:48 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-11-03 22:11:48 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-11-03 22:11:48 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-11-03 22:11:48 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-11-03 22:11:48 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-11-03 22:11:48 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-11-03 22:11:48 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-11-03 22:11:48 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-11-03 22:11:48 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-11-03 22:11:48 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-11-03 22:11:48 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-11-03 22:11:48 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-11-03 22:11:48 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-11-03 22:11:48 INFO] [run:320][39m Running experiment: Employee when database is down
[36m[2022-11-03 22:11:48 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-11-03 22:11:48 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-11-03 22:11:48 INFO] [run:348][39m Rollbacks strategy: default
[36m[2022-11-03 22:11:48 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-11-03 22:11:48 DEBUG] [run:506][39m Running steady-state hypothesis before the method
[32m[2022-11-03 22:11:48 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-11-03 22:11:48 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-11-03 22:11:48 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 22:11:48 INFO] [activity:204][39m Probe: we-can-retrieve-employee-data
[36m[2022-11-03 22:11:48 DEBUG] [activity:221][39m   => succeeded with '{'status': 500, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Thu, 03 Nov 2022 16:41:48 GMT', 'Connection': 'close'}, 'body': {'timestamp': '2022-11-03T16:41:48.601+0000', 'status': 500, 'error': 'Internal Server Error', 'message': 'No message available', 'path': '/employee/all'}}'
[36m[2022-11-03 22:11:48 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 22:11:48 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[36m[2022-11-03 22:11:48 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[31m[2022-11-03 22:11:48 CRITICAL] [run:516][39m Steady state probe 'we-can-retrieve-employee-data' is not in the given tolerance so failing this experiment
[32m[2022-11-03 22:11:48 INFO] [run:458][39m Experiment ended with status: failed
[36m[2022-11-03 22:11:48 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-11-03 22:11:48 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-11-03 22:11:48 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-11-03 22:12:16 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-11-03 22:12:16 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-11-03 22:12:16 DEBUG] [cli:117][39m Using settings file '/home/thushan/.chaostoolkit/settings.yaml'
[36m[2022-11-03 22:12:18 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/thushan/.chaostoolkit/settings.yaml'.
[36m[2022-11-03 22:12:18 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-11-03 22:12:18 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-11-03 22:12:18 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-11-03 22:12:18 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-11-03 22:12:18 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-11-03 22:12:18 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-11-03 22:12:18 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-11-03 22:12:18 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-11-03 22:12:18 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-11-03 22:12:18 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-11-03 22:12:18 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-11-03 22:12:18 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-11-03 22:12:18 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-11-03 22:12:18 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-11-03 22:12:18 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-11-03 22:12:18 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-11-03 22:12:18 INFO] [run:320][39m Running experiment: Employee when database is down
[36m[2022-11-03 22:12:18 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-11-03 22:12:18 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-11-03 22:12:18 INFO] [run:348][39m Rollbacks strategy: default
[36m[2022-11-03 22:12:18 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-11-03 22:12:18 DEBUG] [run:506][39m Running steady-state hypothesis before the method
[32m[2022-11-03 22:12:18 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-11-03 22:12:18 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-11-03 22:12:18 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 22:12:18 INFO] [activity:204][39m Probe: retrieve-employee-data
[36m[2022-11-03 22:12:18 DEBUG] [activity:221][39m   => succeeded with '{'status': 500, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Thu, 03 Nov 2022 16:42:18 GMT', 'Connection': 'close'}, 'body': {'timestamp': '2022-11-03T16:42:18.138+0000', 'status': 500, 'error': 'Internal Server Error', 'message': 'No message available', 'path': '/employee/all'}}'
[36m[2022-11-03 22:12:18 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 22:12:18 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[36m[2022-11-03 22:12:18 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[31m[2022-11-03 22:12:18 CRITICAL] [run:516][39m Steady state probe 'retrieve-employee-data' is not in the given tolerance so failing this experiment
[32m[2022-11-03 22:12:18 INFO] [run:458][39m Experiment ended with status: failed
[36m[2022-11-03 22:12:18 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-11-03 22:12:18 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-11-03 22:12:18 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-11-03 23:14:27 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-11-03 23:14:27 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-11-03 23:14:27 DEBUG] [cli:117][39m Using settings file '/home/thushan/.chaostoolkit/settings.yaml'
[36m[2022-11-03 23:14:28 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/thushan/.chaostoolkit/settings.yaml'.
[36m[2022-11-03 23:14:28 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-11-03 23:14:28 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-11-03 23:14:28 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-11-03 23:14:28 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-11-03 23:14:28 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-11-03 23:14:28 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-11-03 23:14:28 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-11-03 23:14:28 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-11-03 23:14:28 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-11-03 23:14:28 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-11-03 23:14:28 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-11-03 23:14:28 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-11-03 23:14:28 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-11-03 23:14:28 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-11-03 23:14:28 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-11-03 23:14:28 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-11-03 23:14:28 INFO] [run:320][39m Running experiment: Employee when database is down
[36m[2022-11-03 23:14:28 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-11-03 23:14:28 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-11-03 23:14:28 INFO] [run:348][39m Rollbacks strategy: default
[36m[2022-11-03 23:14:28 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-11-03 23:14:28 DEBUG] [run:506][39m Running steady-state hypothesis before the method
[32m[2022-11-03 23:14:28 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-11-03 23:14:28 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-11-03 23:14:28 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 23:14:28 INFO] [activity:204][39m Probe: retrieve-employee-data
[36m[2022-11-03 23:14:29 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Thu, 03 Nov 2022 17:44:29 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': []}'
[36m[2022-11-03 23:14:29 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 23:14:29 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[32m[2022-11-03 23:14:29 INFO] [hypothesis:231][39m Steady state hypothesis is met!
[36m[2022-11-03 23:14:29 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[32m[2022-11-03 23:14:29 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-11-03 23:14:29 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-11-03 23:14:29 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 23:14:29 INFO] [activity:204][39m Action: enable_chaosmonkey
[36m[2022-11-03 23:14:29 DEBUG] [python:33][39m Activity 'enable_chaosmonkey' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-11-03 23:14:29 DEBUG] [activity:221][39m   => succeeded with 'Chaos Monkey is enabled'
[36m[2022-11-03 23:14:29 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 23:14:29 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 23:14:29 INFO] [activity:204][39m Action: configure_assaults
[36m[2022-11-03 23:14:29 DEBUG] [python:33][39m Activity 'configure_assaults' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-11-03 23:14:29 DEBUG] [activity:221][39m   => succeeded with 'Assault config has changed'
[36m[2022-11-03 23:14:29 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 23:14:29 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 23:14:29 INFO] [activity:204][39m Action: configure_repository_watcher
[36m[2022-11-03 23:14:29 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'text/plain;charset=UTF-8', 'Content-Length': '26', 'Date': 'Thu, 03 Nov 2022 17:44:29 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': 'Watcher config has changed'}'
[36m[2022-11-03 23:14:29 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 23:14:29 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-11-03 23:14:29 DEBUG] [run:536][39m Running steady-state hypothesis after the method
[32m[2022-11-03 23:14:29 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-11-03 23:14:29 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-11-03 23:14:29 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 23:14:29 INFO] [activity:204][39m Probe: retrieve-employee-data
[36m[2022-11-03 23:14:29 DEBUG] [activity:221][39m   => succeeded with '{'status': 500, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Thu, 03 Nov 2022 17:44:29 GMT', 'Connection': 'close'}, 'body': {'timestamp': '2022-11-03T17:44:29.696+0000', 'status': 500, 'error': 'Internal Server Error', 'message': 'No message available', 'path': '/employee/all'}}'
[36m[2022-11-03 23:14:29 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 23:14:29 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[36m[2022-11-03 23:14:29 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[31m[2022-11-03 23:14:29 CRITICAL] [run:545][39m Steady state probe 'retrieve-employee-data' is not in the given tolerance so failing this experiment
[32m[2022-11-03 23:14:29 INFO] [run:458][39m Experiment ended with status: deviated
[32m[2022-11-03 23:14:29 INFO] [run:460][39m The steady-state has deviated, a weakness may have been discovered
[36m[2022-11-03 23:14:29 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-11-03 23:14:29 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-11-03 23:14:29 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-11-03 23:18:05 DEBUG] [cli:112][39m ###############################################################################
[36m[2022-11-03 23:18:05 DEBUG] [cli:113][39m Running command 'run'
[36m[2022-11-03 23:18:05 DEBUG] [cli:117][39m Using settings file '/home/thushan/.chaostoolkit/settings.yaml'
[36m[2022-11-03 23:18:06 DEBUG] [settings:30][39m The Chaos Toolkit settings file could not be found at '/home/thushan/.chaostoolkit/settings.yaml'.
[36m[2022-11-03 23:18:06 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-11-03 23:18:06 DEBUG] [__init__:399][39m No controls to apply on 'loader'
[36m[2022-11-03 23:18:06 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-11-03 23:18:06 DEBUG] [caching:35][39m Cached 4 activities
[32m[2022-11-03 23:18:06 INFO] [experiment:58][39m Validating the experiment's syntax
[36m[2022-11-03 23:18:06 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-11-03 23:18:06 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-11-03 23:18:06 DEBUG] [secret:104][39m Done loading secrets
[32m[2022-11-03 23:18:06 INFO] [experiment:109][39m Experiment looks valid
[36m[2022-11-03 23:18:06 DEBUG] [caching:42][39m Clearing activities cache
[36m[2022-11-03 23:18:06 DEBUG] [caching:24][39m Building activity cache...
[36m[2022-11-03 23:18:06 DEBUG] [caching:35][39m Cached 4 activities
[36m[2022-11-03 23:18:06 DEBUG] [configuration:63][39m Loading configuration...
[36m[2022-11-03 23:18:06 DEBUG] [secret:78][39m Loading secrets...
[36m[2022-11-03 23:18:06 DEBUG] [secret:104][39m Done loading secrets
[36m[2022-11-03 23:18:06 DEBUG] [configuration:160][39m Loading dynamic configuration...
[32m[2022-11-03 23:18:06 INFO] [run:320][39m Running experiment: Employee when database is down
[36m[2022-11-03 23:18:06 DEBUG] [__init__:52][39m Initializing controls
[32m[2022-11-03 23:18:06 INFO] [run:344][39m Steady-state strategy: default
[32m[2022-11-03 23:18:06 INFO] [run:348][39m Rollbacks strategy: default
[36m[2022-11-03 23:18:06 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-11-03 23:18:06 DEBUG] [run:506][39m Running steady-state hypothesis before the method
[32m[2022-11-03 23:18:06 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-11-03 23:18:06 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-11-03 23:18:06 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 23:18:06 INFO] [activity:204][39m Probe: retrieve-employee-data
[36m[2022-11-03 23:18:10 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Thu, 03 Nov 2022 17:48:10 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': []}'
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 23:18:10 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[32m[2022-11-03 23:18:10 INFO] [hypothesis:231][39m Steady state hypothesis is met!
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[32m[2022-11-03 23:18:10 INFO] [run:607][39m Playing your experiment's method now...
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 23:18:10 INFO] [activity:204][39m Action: enable_chaosmonkey
[36m[2022-11-03 23:18:10 DEBUG] [python:33][39m Activity 'enable_chaosmonkey' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-11-03 23:18:10 DEBUG] [activity:221][39m   => succeeded with 'Chaos Monkey is enabled'
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 23:18:10 INFO] [activity:204][39m Action: configure_assaults
[36m[2022-11-03 23:18:10 DEBUG] [python:33][39m Activity 'configure_assaults' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-11-03 23:18:10 DEBUG] [activity:221][39m   => succeeded with 'Assault config has changed'
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 23:18:10 INFO] [activity:204][39m Action: configure_repository_watcher
[36m[2022-11-03 23:18:10 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'text/plain;charset=UTF-8', 'Content-Length': '26', 'Date': 'Thu, 03 Nov 2022 17:48:10 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': 'Watcher config has changed'}'
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'method'
[36m[2022-11-03 23:18:10 DEBUG] [run:536][39m Running steady-state hypothesis after the method
[32m[2022-11-03 23:18:10 INFO] [hypothesis:182][39m Steady state hypothesis: Employee data is available
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 23:18:10 INFO] [activity:204][39m Probe: retrieve-employee-data
[36m[2022-11-03 23:18:10 DEBUG] [activity:221][39m   => succeeded with '{'status': 200, 'headers': {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Date': 'Thu, 03 Nov 2022 17:48:10 GMT', 'Keep-Alive': 'timeout=60', 'Connection': 'keep-alive'}, 'body': []}'
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 23:18:10 DEBUG] [hypothesis:221][39m allowed tolerance is 200
[32m[2022-11-03 23:18:10 INFO] [hypothesis:231][39m Steady state hypothesis is met!
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'hypothesis'
[32m[2022-11-03 23:18:10 INFO] [run:893][39m Let's rollback...
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-11-03 23:18:10 INFO] [rollback:30][39m Rollback: disable_chaosmonkey
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[32m[2022-11-03 23:18:10 INFO] [activity:204][39m Action: disable_chaosmonkey
[36m[2022-11-03 23:18:10 DEBUG] [python:33][39m Activity 'disable_chaosmonkey' loaded from '/home/thushan/.venvs/chaostk/lib/python3.8/site-packages/chaosspring/actions.py'
[36m[2022-11-03 23:18:10 DEBUG] [activity:221][39m   => succeeded with 'Chaos Monkey is disabled'
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'activity'
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'rollback'
[32m[2022-11-03 23:18:10 INFO] [run:458][39m Experiment ended with status: completed
[36m[2022-11-03 23:18:10 DEBUG] [__init__:399][39m No controls to apply on 'experiment'
[36m[2022-11-03 23:18:10 DEBUG] [__init__:91][39m Cleaning up controls
[36m[2022-11-03 23:18:10 DEBUG] [caching:42][39m Clearing activities cache
